wandb_version: 1

clip_factor:
  value: 10
clipping:
  value: false
feedback_scaling:
  value: 1
hs:
  value: 50
lr:
  value: 0.001
max_length:
  value: 9
momentum:
  value: 0
nonlin:
  value: sigmoid
num_cycles:
  value: 200000
num_letters:
  value: 10
opt:
  value: sgd
stopping_criteria:
  value: 0.58
test_list_length:
  value: 6
test_size:
  value: 5000
train_batch:
  value: 1
