wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1657817606
    t:
      1:
      - 55
      3:
      - 16
      4: 3.8.10
      5: 0.12.21
      8:
      - 1
      - 5
clip_factor:
  desc: null
  value: 10
clipping:
  desc: null
  value: false
feedback_scaling:
  desc: null
  value: 1.0
hs:
  desc: null
  value: 200
list_length:
  desc: null
  value: 9
lr:
  desc: null
  value: 0.001
nonlin:
  desc: null
  value: sigmoid
num_cycles:
  desc: null
  value: 200000
num_letters:
  desc: null
  value: 10
opt:
  desc: null
  value: SGD
stopping_criteria:
  desc: null
  value: 0.58
test_list_length:
  desc: null
  value: 6
test_size:
  desc: null
  value: 5000
train_batch:
  desc: null
  value: 1
