wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1657651502
    t:
      1:
      - 1
      - 51
      - 55
      2:
      - 1
      - 51
      - 55
      3:
      - 1
      - 16
      4: 3.8.10
      5: 0.12.21
      8:
      - 5
clip_factor:
  desc: null
  value: 10
clipping:
  desc: null
  value: false
feedback_scaling:
  desc: null
  value: 1.0
hs:
  desc: null
  value: 200
is:
  desc: null
  value: 11
list_length:
  desc: null
  value: 9
loss_func:
  desc: null
  value: kl
lr:
  desc: null
  value: 0.001
nonlin:
  desc: null
  value: sigmoid
optimizer:
  desc: null
  value: SGD
os:
  desc: null
  value: 11
stopping_criteria:
  desc: null
  value: 0.58
test_list_length:
  desc: null
  value: 6
